export const tweets = [
  {
    created_at: "Sat Apr 13 22:35:46 +0000 2019",
    id: 1117194697053745200,
    id_str: "1117194697053745164",
    text:
      "RT @Joansustacha: Viendo esto, no hay futuro eléctrico bajo esta administración #Sinluz https://t.co/5Hgd2anZI6",
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 3433714635,
      id_str: "3433714635",
      name: "Fulldenuncias",
      screen_name: "fulldenuncias",
      location: null,
      url: null,
      description: null,
      translator_type: "none",
      protected: false,
      verified: false,
      followers_count: 595,
      friends_count: 226,
      listed_count: 4,
      favourites_count: 78,
      statuses_count: 5886,
      created_at: "Fri Aug 21 03:22:38 +0000 2015",
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: "es",
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1081617805705953280/cuMis5Zp_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1081617805705953280/cuMis5Zp_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/3433714635/1515121407",
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
      created_at: "Sat Apr 13 21:41:42 +0000 2019",
      id: 1117181088441487400,
      id_str: "1117181088441487371",
      text:
        "Viendo esto, no hay futuro eléctrico bajo esta administración #Sinluz https://t.co/5Hgd2anZI6",
      display_text_range: [0, 69],
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      truncated: false,
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 64211814,
        id_str: "64211814",
        name: "Joan Sustacha",
        screen_name: "Joansustacha",
        location: null,
        url: null,
        description:
          "Locutor, fanatico de la aviacion y los multicampeones Tigres de Aragua",
        translator_type: "none",
        protected: false,
        verified: false,
        followers_count: 236,
        friends_count: 438,
        listed_count: 3,
        favourites_count: 666,
        statuses_count: 7694,
        created_at: "Sun Aug 09 17:20:52 +0000 2009",
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        lang: "es",
        contributors_enabled: false,
        is_translator: false,
        profile_background_color: "C0DEED",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1757974605/Tigres-de-Aragua6_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1757974605/Tigres-de-Aragua6_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/64211814/1401571177",
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      quoted_status_id: 1116894230511792100,
      quoted_status_id_str: "1116894230511792128",
      quoted_status: {
        created_at: "Sat Apr 13 02:41:50 +0000 2019",
        id: 1116894230511792100,
        id_str: "1116894230511792128",
        text:
          'Corpoelec publica con "orgullo" esta foto. Dos trabajadores son levantados dentro de una pala mecánica para lavar u… https://t.co/NbuxMkr7Yv',
        display_text_range: [Array],
        source:
          '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
        truncated: true,
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        extended_tweet: [Object],
        quote_count: 36,
        reply_count: 49,
        retweet_count: 697,
        favorite_count: 229,
        entities: [Object],
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        filter_level: "low",
        lang: "es"
      },
      quoted_status_permalink: {
        url: "https://t.co/5Hgd2anZI6",
        expanded: "https://twitter.com/watcher_ven/status/1116894230511792128",
        display: "twitter.com/watcher_ven/st…"
      },
      is_quote_status: true,
      quote_count: 1,
      reply_count: 0,
      retweet_count: 5,
      favorite_count: 0,
      entities: {
        hashtags: [Array],
        urls: [Array],
        user_mentions: [],
        symbols: []
      },
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      filter_level: "low",
      lang: "es"
    },
    quoted_status_id: 1116894230511792100,
    quoted_status_id_str: "1116894230511792128",
    quoted_status: {
      created_at: "Sat Apr 13 02:41:50 +0000 2019",
      id: 1116894230511792100,
      id_str: "1116894230511792128",
      text:
        'Corpoelec publica con "orgullo" esta foto. Dos trabajadores son levantados dentro de una pala mecánica para lavar u… https://t.co/NbuxMkr7Yv',
      display_text_range: [0, 140],
      source:
        '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
      truncated: true,
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 59029006,
        id_str: "59029006",
        name: "Watcher",
        screen_name: "Watcher_Ven",
        location: "Ciudad Guayana, Venezuela",
        url: null,
        description: null,
        translator_type: "regular",
        protected: false,
        verified: false,
        followers_count: 80937,
        friends_count: 28954,
        listed_count: 315,
        favourites_count: 22,
        statuses_count: 26180,
        created_at: "Wed Jul 22 04:03:21 +0000 2009",
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        lang: "es",
        contributors_enabled: false,
        is_translator: false,
        profile_background_color: "022330",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: true,
        profile_link_color: "0084B4",
        profile_sidebar_border_color: "A8C7F7",
        profile_sidebar_fill_color: "C0DFEC",
        profile_text_color: "333333",
        profile_use_background_image: true,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/853026464610037760/dk2b_bHl_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/853026464610037760/dk2b_bHl_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/59029006/1538666579",
        default_profile: false,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      extended_tweet: {
        full_text:
          'Corpoelec publica con "orgullo" esta foto. Dos trabajadores son levantados dentro de una pala mecánica para lavar unos aisladores. Las normas de seguridad se las pasan por el cu... / ¿No hay camión cesta? https://t.co/6HOMVn7z8U',
        display_text_range: [Array],
        entities: [Object],
        extended_entities: [Object]
      },
      quote_count: 36,
      reply_count: 49,
      retweet_count: 697,
      favorite_count: 229,
      entities: { hashtags: [], urls: [Array], user_mentions: [], symbols: [] },
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      filter_level: "low",
      lang: "es"
    },
    quoted_status_permalink: {
      url: "https://t.co/5Hgd2anZI6",
      expanded: "https://twitter.com/watcher_ven/status/1116894230511792128",
      display: "twitter.com/watcher_ven/st…"
    },
    is_quote_status: true,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: {
      hashtags: [[Object]],
      urls: [[Object]],
      user_mentions: [[Object]],
      symbols: []
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: "low",
    lang: "es",
    timestamp_ms: "1555194946908"
  }
];
